### ISSUE TITLE
SciPy 2019 tutorial plan

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#174]
This issue collects to-do items and planning for the SciPy 2019 tutorials, subsuming previous such issues #42, #90, and #97. Bigger tasks we expect to do before the tutorial:

- [x] Introduction 01 should be replaced with a short demo (10-15min) (e.g. datashader 1billion dashboard, gapminders, nb with other types of plots) [#188]
- [x] Move Introduction 01 out of the tutorial itself, to be next to background nb as an overview (jsignell) [#188]
- [x] Reduce total amount of material expected to be covered

NEW WRITING:
- [x] Boost focus on Panel
- [ ] Boost coverage of libraries other than Bokeh
- [x] More/better/more-hands-on exercises
- [x] Reduce overlap between tutorial sections
- [x] Try to make the difference between holoviews and hvplot more explicit in the text.
- [ ] Review feedback from prior tutorials (incorporated below)
    * [ ] Add list of references and weblinks for further exploration
    * [ ] Have a list of conference presentations coming up that use these tools (@jbednar)
    * [ ] Explain what these packages will _not_ do (@jbednar)
    * [ ] How do other tools fit in? Seaborn, ggpy, etc.  (@jbednar)
    * [x] Early examples were basic, then later ones quickly became impenetrable, so that we could only see what CAN be done, not HOW to do it.  Try to balance better.

ENV MANAGEMENT:
- [x] Move topics from datashader and holoviews sites into pyviz, as most combine multiple tools and make good launching-off points. (jsignell)
- [x] Streamline conda environment instructions/setup: (jsignell)
    * [x] Only install holoviews and not geoviews
    * [x] Remove conda-forge from list of channels
    * [x] Update pinning, if needed
    * [x] Measure the time to build the conda environment, and see if it can be improved if not reasonable
    * [ ] Test conda install on Windows
    * [x] Make sure everything is pip-installable as well as conda-installable (#81) (but warn pip users that they are on their own)

Other to-do items we hope to be able to get to as well:

- [x] Remove numbers from the website versions of notebooks, leaving them in the .ipynb files to show ordering (jsignell)
- [x] Remove ! and > characters in the prompts in the installation instructions; Windows users (in particular) were copy-pasting this into their command prompt (jsignell)
- [ ] Provide a binder or similar environment that users can use if their environment doesn't work (https://github.com/pyviz/pyviz/issues/98)
- [ ] Separate suggested diversions/more detail more clearly from what to do next in the tutorial.
- [x] Add multiple plotting libraries to the first tutorial sections
- [ ] How to handle matplotlib inline and discuss it
- [x] Make sure data isn't redownloaded when updating, when following our instructions
- [ ] Merge in content from the PyData Cookbook (Jim; https://github.com/pydata/pydata-cookbook/pull/26)
- [ ] Change 08_Custom_Interactivity.ipynb to use new RangeSelect tool
- [x] Mention new Links feature that will allow custom interactivity without needing a live server
- [x] Introduce DynamicMap and HoloMap properly
- [x] 09_Operations_and_Pipelines.ipynb starts using datashader without introducing it/why to use it/that it will be described in the next section?
- [x] Tighten up descriptions -- Q: is the whole thing a tutorial, or is each notebook a tutorial? A: Each nb is a section
- [x] Reduce overlap with holoviews.org, primarily just pointing people from pyviz.org to holoviews.org
- [x] Should fold in tutorial A1's material somewhere; it's odd to have it in an appendix. It made sense when the tutorial was smaller, but now that there is always more material than can be covered, it's confusing to have it separate, so that the other material can't tell whether these concepts have been introduced.

Seemingly unrelated tasks mentioned in previous issues, collected here to avoid forgetting them:

- [ ] Add a section to pyviz.org with links to maintainer-focused projects (nbsite, nbval, nbsmoke, autover, etc.)
- [ ] Make pyviz tests cover installing as a package and other new functionality (#81)
- [ ] Add twitter feed listening to multiple projects
- [ ] Need automated scripts for making at least the first pass at the site logo and favicon bitmaps from a transparent SVG source; currently edited those by hand for pyviz.org and other project sites have non-transparent logos. (See pyviz/nbsite#40)

**Comment by drrmmng** [comment]
Sorry for being a bit off-topic but I'm so hyped for this! :heart_eyes:

**Comment by jlstevens** [comment]
Discussing the plan with @jbednar and @philippjfr, we came up with this outline:

### General notes

We would like the whole tutorial to be based on some large dataset (probably columnar). Initially, we would work with a vastly reduced data size by taking some set of meaningful statistical aggregates.

### 1. Overview of the tutorial/setup (@jbednar)

Making sure everyone has the data, has configured their environments etc.

### 2: Introduction to Panel and the different types of things that it can display. (@philippjfr )

Starting with non-plotting types: e.g markdown, HTML, pandas dataframes, PNG images. Introduce panes and `pn.Row`/`pn.Column`

Then talk about the plotting libraries that can be used. The existing dashboard that illustrates the message is gapminder.

#### Exercise 1: Using a mix of visualizable types (including plots in some library if you want, optionally, but warning that matplotlib is a pain here), create a panel layout and serve it with `serveable`.

Then introduce `@depends` to set a callback on `.value` change to introduce widgets.

#### Exercise 2: Add widgets in this way to control the dashboard elements built in exercise 1.

### 3: Introduction to the `.plot` API and associated libraries. (@jsignell)

Libraries using this interface: pandas `.plot`, xarray `.plot`?, quick intro to cufflinks, hvplot.

Quick easy way to generate simple plots.

#### Exercise 3: Add some visualizations via the `.plot` API to the dashboard elements built in exercise 2.

#### 3b: Link to `HoloViews` from `hvplot` output ('shortcuts not dead ends')

Deconstruct hvplot output to show what individual elements are. Show more involved repr with `NdOverlay`. Discuss that these are are compositional objects. Show `DynamicMap` output from `hvplot`.

### 4: Introduction to HoloViews for building custom interactivity (i.e not possible with `.plot` alone). (@jlstevens)

Previously this tutorial was far too long. The goal now is to get to a linked plot example (like glaciers) where you have some box selection on one plot to update some other linked plot.

#### Topics that need some level of detail: Elements, Composition, Containers, DynamicMap, LinkedStreams.

#### Topics that may appear once at some point but not discussed at length (though linked to appropriate docs for more detail): Dimensions, `.opts`, `HoloMap`, non-linked streams.

#### Exercise 4: Build a linked visualization with holoviews.

### 5: Datashader (via holoviews operations) (@jbednar)

 Introduction to how datashader works with mention of native API (that lacks interactivity).To start,  can load the large dataset with parquet and then use `hvplot`.

Then some discussion how the datashader operations uses elements, dynamicmaps, streams.

#### Exercise 5: Build a dashboard visualizing the whole of the provided dataset with datashader.

### 6: Building advanced dashboards.  (@philippjfr  and everybody else)

Goal is to use all the concepts introduced to build a panel dashboard using the features that have been introduced. Possible exercises:

#### Exercise 6: Build a dashboard consisting of 1) a plot using any library of choice showing some statistical aggregate of the large data. A datashader component showing the full dataset. A custom interactivity component (e.g reusing the linked visualization exercise above?)

#### Exercise 7: Build an efficient, compositional dashboard where data and plots are re-computed/redrawn as necessary. Concepts from the generalized datashader dashboard.

### 5: Conclusion

Summary, more pointers to docs, mention of topics not covered (streaming data? geographic? networks etc).

# Other notes

* Group exercises as well as individual exercises?
* The existing tutorial can be trimmed to be repurposed as a holoviews only tutorial.
* I think the eclipses example could be made into a nice topic example.

**Comment by jbednar** [comment]
Looks good. Some alternatives we should consider:

- Items 2 and 3 can be swapped. Current story: you can use panel for anything, then here are some plots, then here are some plots in panel.  New story would be: Here are some simple ways to get plots, here is how to put those in a panel, you can use panel for anything.  I don't have a strong preference.

- Datashader can be introduced in the hvplot section, maybe saying that we'll dive into the details later. And then later we can explain how it works, with operations, streams, etc.

The final exercise is fairly ambitious; would be good to have some alternative that people could try that requires less mastery.

**Comment by jsignell** [comment]
Are Exercises 6 and 7 intended to be done with people's own data? Should we tell people to come with a dataset in mind?

**Comment by jbednar** [comment]
I think we shouldn't tell people ahead of time to bring their own, as it will open up many cans of worms and put us in the situation of trying to support all their arbitrary ELT problems.  Instead, I think we should mention at key points that if they are comfortable with Python and already have suitable datasets lying around, feel free to use them here.  That way people won't feel like they _have_ to do this, but those who are ready to can do so.

**Comment by jlstevens** [comment]
@jbednar @philippjfr While discussing our tutorial plans with @jsignell, we thought it might be good to try and follow a few principles:

* Like our previous tutorials, it should be possible to follow online (but much shorter).
*   Exercises should complement this base experience i.e you shouldn't *have* to do the exercises to follow the tutorial (even if the exercises are helpful and recommended).
* For this reason, we should expect that someone doing the tutorial by themselves online at a decent pace (i.e not too rushed) should take maybe 2/3rds the time allocated for the SciPy tutorial (so 2-3 hours?). Then this leaves 1/3rd of the time for doing exercises, helping people get set up etc.

**Comment by jlstevens** [comment]
@jbednar @philippjfr @jsignell Just to summarize the plans for the HoloViews section that I've discussed with Julia:

* Julia introduces some nice plots analyzing earthquake magnitude in the `.plot` section. There are plenty of good plots there that can be subsampled/subselected to demonstrate linking. It will be easier to talk about the mechanics of streams etc if I can re-create some of those same plots using HoloViews.

* The main inspiration and goal for this section is to create an earthquake equivalent to the glaciers dashboard (though just using HoloViews at this stage as Panel will be discussed again later in the tutorial). Just link glaciers there will be a map of earthquakes where you can box select and at least two linked statistical plots.

* To avoid needing datashader at this point in the tutorial for the map plot,  we can focus on a single country (say Japan which should be more interesting) and one earthquakes greater than a minimum magnitude. This magnitude filter could even be a slider itself with a minimum bound set that is sufficient to avoid needing datashader.

* One idea I discussed with Julia is to do a daily/weekly/monthly time average of magnitudes within the box selected region on the map. The idea is that we can choose the granularity of the temporal sampling and the length of history to keep the data size plotted manageable. The other linked plot could be the distribution of magnitudes in the selected region.

* One good idea that is HoloViews only would be to add annotations such as text/arrows etc. Perhaps we could label a number one or two of the highest magnitude earthquakes on the map. Any other suggestions?

**Comment by jsignell** [comment]
Action items [due midday July 3rd]

 - [x] @jsignell add banner to index and all notebooks saying we're working on them and when they'll be ready
 - [x] @jsignell figure out the update process for how to get the new notebooks without re-downloading data
 - [x] @jlstevens write an outline for 06_Custom_Interactivity.ipynb
     - [x] include hv.help
 - [x] @philippjfr push 02_Introduction_to_Panel.ipynb
 - [x] @philippjfr push 03_Panel_Widgets.ipynb
 - [x] @jbednar write 07_Working_with_Large_Datasets.ipynb
 - [x] @philippjfr outline of 08_Building_Advanced_Dashboards.ipynb

Afterwards:
 - [x] do a release of holoviz 

Action items [due by Monday July 8th morning]
 - [x] do a fresh release of holoviz 
 - [x] make sure setup.ipynb has good instructions

**Comment by jsignell** [comment]
**NOTE:** If you change the name of a notebook: you need to change the links in:
- examples/tutorial/index.rst
- doc/tutorial/index.rst
- in any notebooks that link to it
