### ISSUE TITLE
Post-SciPy 2019 tutorial improvements

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#202]
- [ ] Review https://github.com/pyviz/holoviz/issues/174 and collect remaining issues here
- [x] 02_Building_Panels:
    * [x] Integrate the interact example better -- use it for the base, or at least return to it at the end of the notebook to show what we can do with the tools we now have at this point in the tutorial
- [x] 03_Interlinked_Panels: 
    * [x] Can the examples be made more relevant to the overall tutorial dataset/task? 
- [ ] Add links for further study -- having seen this one example, e.g. interact, where can we find all the details?
- [ ] Review tutorial in the context of the website -- does it all add up?
- [ ] Try out old tutorial content links -- can we make those links work again?
- [ ] Take content from old tutorial and migrate it to the appropriate site, e.g. examples.pyviz.org or an individual project (holoviews, hvPlot, GeoViews, etc.)
- [ ] Try to make sections  04-06 less heavy; they will probably bog users down.
- [ ] Fix  tap/hover tool overwriting in tutorial (6?)
- [x] Fix '##' + text example; should be something more obvious and dramatic as a transformation
- [x] Avoid having to talk about Points versus Scatter; maybe make a Pandas pull request to allow either one? In any case, spend less time on it.
- [ ] Improve mpl examples, e.g. with `%matplotlib widget` and showing more advanced features
- [ ] Add other .plot API examples from other libraries?
- [ ] Import swatches (noqa)
- [ ] Bring out .apply better in the last section; the material may be there, but at least in the recording it's not clear.

Related, but not directly about the tutorial:
- [ ] Make sure the Datashader dashboard has a running instance, and link it from the Panel homepage
- [ ] Make a non-class version of the Datashader dashboard
- [ ] Make sure all the various Panel examples are deployed the way we want them, either on examples or on demos; they seem haphazard right now
- [ ] Link to a running Euler example and other appropriate examples from Panel

**Comment by jsignell** [comment]
- [x] 00_Setup.ipynb 
  - [x] Should include python-snappy check for pip users and text for fail.
  - [x] No data should prompt users with `Earthquakes dataset not found; please run "holoviz fetch-data --path ..".`
  - [x] Don't need bokeh sampledata.
  - [x] Bad link to `07_Working_with_Large_Datasets.ipynb`
- [ ] Set up a remote instance (binder or AE).

**Comment by jlstevens** [comment]
- [ ] Avoid using dask (i.e to avoid `.compute()` calls) unless there is a needed performance improvement.
- [ ] Avoid the need for `python-snappy` which cannot be pip installed. See #220
- [ ] Fix for where the hover tool was being overridden in `.opts`.

**Comment by jbednar** [comment]
- [x] Remove geoviews from Datashader dashboard
- [x] Add intake to tutorial environment?  Not actually used,  though.
- [x] Finish moving all apps to examples.pyviz.org (Attractors, Dashboard, etc.)
- [ ] Use SciPy talk as Getting Started? No linking example yet,  though.
- [x] Add documentation for wrapping external JS libraries in Panel
- [ ] Add examples of doing work in JS  instead of Python to support static export
- [ ] Replace Panel gettiing-started with new occupancy example.
- [ ] Update Panel getting-started to properly describe reactive APIs (https://github.com/pyviz/panel/issues/510)

**Comment by jbednar** [comment]
~~- [ ] Panel JupyterLab instructions need to say ``conda install nodejs`~~

**Comment by jbednar** [comment]
- [ ] Really need to work on behavior for Datashader when zoomed in and individual points are visible; at least need to implement dynspread for rasterize()
- [ ] Add pointer to mpl_scatter_density from Datashader

**Comment by jbednar** [comment]
More issues, after acon20:

- [ ] Make Exercise 1 not refer to material not yet introduced (explicitly creating widgets)
- [ ] If giving a 2 hour version like acon20.ipynb again, either should start with Overview.ipynb or Panel's tutorial and add exercises, or should add another notebook after basic plotting that brings Panel and hvPlot together in a simple way.
- Issues with final app:
  * [ ] works strangely with zooming
  * [ ] state initially selected should be more interesting    
  * [ ] shows `nan` in top left -- should be 0
  * [ ] needs to display some text explaining what to do (how to use the app)
- [ ] Need to package final app for examples.pyviz.org -- maybe move the tutorial there as a subdirectory, using the same environment?
- [ ] 08*.ipynb displays a warning in Juypter: /Users/jbednar/miniconda3/envs/holoviz-tutorial/lib/python3.7/site-packages/xarray/core/nanops.py:142: RuntimeWarning: Mean of empty slice return np.nanmean(a, axis=axis, dtype=dtype)
- [ ] small_df causes Bokeh hiccups; make smaller?  Or limit hover?

**Comment by jbednar** [comment]
Subsumed by #275.
