### ISSUE TITLE
Website improvements TODO

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#26]
(draft - please feel free to edit)

* [ ] go through all inter-notebook links - some seem to go nowhere?
* [ ] do something for apps
* [x] build exercises and verify links to them
* [ ] replace tutorial/index with tutorial/00_Welcome
* [x] regenerate logo and favicon (e.g. for transparency)  
* [x] customizing visual appearance notebook is skipped (#6)
* [ ] add gallery
* [x] canonical location now pyviz.org, not https://pyviz.github.io/pyviz; need to update in conf.py (and see https://github.com/pyviz/nbsite/issues/41 for note that this domain should also be put into CNAME for pyviz.org)

**Comment by jsignell** [comment]
Should examples.pyviz.org be linked from gallery or topics?

**Comment by jbednar** [comment]
Good question.  Topics, deep dives, examples, gallery, ...  many possible things it could be called.

**Comment by jbednar** [comment]
Subsumed by #275.
