### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#275]
Subsumes #26, #174, and #202, listing the remaining open to-do items about the tutorials.

- Review the existing tutorial content:
  * [ ] Are there any broken inter-notebook links? At some point there were some that went nowhere.
  * [x] Are there any warnings generated in the notebooks?
  * [ ] Review tutorial in the context of the website (as opposed to Jupyter)

- Improve the existing tutorial content:
  * [ ] Improve overall "finish" of the examples to make them look and feel awesome (see #260)
  * [x] Improve the earthquake plot from tutorial front page and 05_Composing_Plots (see #260)
  * [x] Fix logz option in earthquake plot in 05_Composing_Plots (see #260)
  * [x] Add a greyed out watermark or other unmissible indication for interactive content not interactive on the website (see #260)
  * [x] Simplify 01_Overview so that an inexperienced person can understand and appreciate it. Perhaps replace with 1-4min video showcase of solid, compelling, fast examples?
  * [ ] Bring "Workflow from data to decision" content content front and center (see https://github.com/holoviz/holoviz/issues/260#issuecomment-672706218)
  * [x] For simplicity, avoid using dask (i.e to avoid `.compute()` calls) unless it matters for performance
  * [x] Update examples to use rasterize() + dynspread instead of datashade() + dynspread
  * [x] Improve mpl examples, e.g. with `%matplotlib widget` and showing more advanced features
  * [x] Avoid the need for `python-snappy` which cannot be pip installed. See #220
  * [x] Make Exercise 1 not refer to material not yet introduced (explicitly creating widgets)
  * [x] small_df causes Bokeh hiccups in tutorial 4; make smaller?  Or limit hover?
  * [x] Fix for where the hover tool was being overridden in `.opts`. (where?)
  * [ ] If giving a 2 hour version like acon20.ipynb again, either should start with Overview.ipynb or Panel's tutorial and add exercises, or should add another notebook after basic plotting that brings Panel and hvPlot together in a simple way.
  
- Possible new tutorial content:
  * [ ] Boost coverage of libraries other than Bokeh, e.g. other .plot API examples from other libraries
  * [ ] Discuss how other tools fit in? Seaborn, ggpy, etc.
  * [ ] Explain what these packages will _not_ do
  * [ ] Add more links for further study -- having seen this one example, e.g. interact, where can we find all the details?
  * [ ] Add list of references and weblinks for further exploration
  * [ ] Separate suggested diversions/more detail more clearly from what to do next in the tutorial.
  * [ ] Merge in content from the PyData Cookbook (https://github.com/pydata/pydata-cookbook/pull/26)
  * [ ] Change interactive examples to use new RangeSelect tool
  * [ ] Add examples of doing work in JS instead of Python to support static export

- Review app examples in the tutorial:
  * [x] Should we get rid of separate .py apps except as examples, with the main content all in notebooks for tutorial purposes?
  * [x] If not folded into notebooks, apps and their code presumably need to be reorganized and cleaned up.
  * [x] App (which one?) works strangely with zooming?
  * [x] App (which one?) state initially selected should be more interesting    
  * [x] App (which one?) shows `nan` in top left -- should be 0
  * [ ] Should display some text explaining what to do (how to use the app)
  * [ ] Need to package final apps for examples.pyviz.org -- maybe move the tutorial there as a subdirectory, using the same environment?

- Other holoviz.org suggestions:
  * [ ] Have a list of conference presentations coming up that use these tools (@jbednar)
  * [x] Add twitter feed listening to multiple projects
  * [ ] Add gallery
  * [ ] Link examples.pyviz.org from topics or somewhere else prominent
  

- Other related HoloViz to-do items not directly about the tutorials or the holoviz.org site:
  * [ ] Take content from old tutorial and migrate it to the appropriate site, e.g. examples.pyviz.org or an individual project (holoviews, hvPlot, GeoViews, etc.)
  * [x] Make sure the Datashader dashboard has a running instance, and link it from the Panel homepage
  * [ ] Make a non-class version of the Datashader dashboard (now at https://anaconda.org/jbednar/dashboard_barewidgets/notebook, but still not linked in the docs)
  * [ ] Make sure all the various Panel examples are deployed the way we want them, either on examples or on demos; they seem haphazard right now
  * [ ] Link to a running Euler example and other appropriate examples from Panel
  * [ ] Replace Panel getting-started with new occupancy example?
  * [ ] Update Panel getting-started to properly describe reactive APIs (https://github.com/pyviz/panel/issues/510)
  * [x] Need to improve Datashader behavior for zooming in with small numbers of points; probably have to update eq_hist in both shade() and Bokeh
  * [x] Add pointer to mpl_scatter_density from Datashader
  * [ ] Add a section to holoviz.org with links to maintainer-focused projects (nbsite, nbval, nbsmoke, autover, etc.)
  * [ ] Need automated scripts for making at least the first pass at the site logo and favicon bitmaps from a transparent SVG source; currently edited those by hand for pyviz.org and other project sites have non-transparent logos. (See pyviz/nbsite#40)

**Comment by jbednar** [comment]
New items collected from https://github.com/holoviz/holoviz/pull/283 after recording the SciPy 2021 tutorial:

- [ ] Fix interactivity warning (CSS?) (JL)
- [ ] Github link for holoviz.org points to panel, not holoviz (JL)
- [ ] Update times on the schedule to reflect the actual time taken to cover it
- [ ] Add a clean, pure-python version of the final dashboard code from 06 and later notebooks, to demonstrate working outside of Jupyter. (Pam)
- [ ] Remove USGS logo download from the .yml file; should just be in assets/. (JL)
- [ ] Document binder setup on website (PJFR)
- [ ] Update website (preferably with the new sphinx theme)
- [ ] Run a link checker on the final version (ideally set up CI to give you a checkable listing of link issues)
- [ ] 04_Interlinked_Plots.ipynb: For Linked-brushing-across-element-types, the map plot aspect ratio is still broken in some cases (PJFR)
- [ ] 04_Interlinked_Plots.ipynb: For Linked-brushing-across-element-types, does lasso selection have any effect? (PJFR)
- [ ] 05_Interactive_Pipelines.ipynb: Some versions of Filtering-the-earthquakes-on-a-map flicker a lot; need to talk about how to avoid that. (discussion)
- [ ] Improve the final app
- [ ] Fix pn.state.template.show() from a notebook (PJFR)
- [ ] Test better on Windows
- [ ] Make final metapackage release (and remove package-building machinery from this repo?) (JL)
- [ ] Add repr for bound objects (as a separate pn.show?) amd add param.bind (JB/JL/PJFR)
- [ ] Document how to use .interactive with ipywidgets, or at least point to the docs on that. (PJFR)
- [ ] Add instructions for using dask, separate from the main tutorial, e.g. as a link to a PR showing what changes are needed for Dask. (JB)
