### ISSUE TITLE
 Analytics with plausible.io

### ISSUE THREAD

**Issue by maximlt** [holoviz/holoviz#321]
Currently the HoloViz websites have no analytics in place (Google Analytics was removed). A solution that has recently emerged in the PyData ecosystem is [plausible.io](https://plausible.io/), a lightweight, user-friendly and open-source web analytics (at least that's what they say!). The Pydata Sphinx Theme supports it since version 0.9.0 and actually [recommends it](https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/analytics.html#analytics-and-usage-services) over Google Analytics. In light of the documentation work we intend to do, I suggest we set up `plausible.io` on the following websites:

- [ ] panel.holoviz.org
- [ ] hvplot.holoviz.org
- [ ] holoviews.org
- [ ] holoviz.org
- [ ] examples.pyviz.org
- [ ] param.holoviz.org
- [ ] datashader.org
- [ ] geoviews.org
- [ ] lumen.holoviz.org
- [ ] colorcet.holoviz.org

**Comment by droumis** [comment]
we moved to goatcounter bc plausible == $$$
