### ISSUE TITLE
Post-tutorial updates

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#42]
pyviz.org is in pretty good shape after preparing and polishing a series of releases yesterday that updated all the materials and the website. There are a few to-do items now that we didn't have time for or are based on having given the tutorial live yesterday:

Quick:

- [x] Fix PyViz logo in upper left of website; is being overwritten by "PyViz".  Maybe replace with wordmark instead of text?
- [x] Fix formatting of images in https://pyviz.github.io/pyviz/tutorial/01_Workflow_Introduction.html
- [x] Change theme colors to work with logo
- [x] Make the paragraph symbol on intrapage links much lighter gray to make it nearly invisible
- [x] Mention `conda update conda ; conda update conda` in the installation instructions (if an older conda was on their systems, installation was failing to find packages from the main channel, possibly the noarch ones)
- [x] Add big copy of logo to front page
- [x] Add project logos and some viz to the pyviz.org front page
- [x] Add link to osm-1billion example (and mention how to download the data)
- [x] Replace .opts with .options in examples
- [x] Update holoviews, geoviews, param, parambokeh, and the corresponding HoloViews version number in 00_Setup.ipynb.
- [ ] Merge in content from the PyData Cookbook
- [x] Fix [nbsite#59](https://github.com/pyviz/nbsite/issues/59) (broken links for downloading notebooks, e.g. the one on http://pyviz.org/tutorial/11_Streaming_Data.html)
- [x] Add links from each tutorial notebook on to the next
- [x] Fix non-mpl options in 02 (again!)
- [x] Fix data download path

Medium:

- [x] Do `bokeh.sampledata.download()` in the doc build in Travis to avoid having 00 Welcome fill up with [downloading messages](https://pyviz.github.io/pyviz/tutorial/00_Welcome.html)
- [x] Move paragraphs of text 00 Welcome into index.html, leaving just the mechanical bits as part of the first tutorial.
- [ ] Simplify the 01 Workflow notebook; lots of good material, but needs to be quicker
- [ ] Pin any dependencies that could conceivably vary? (#25)
- [ ] Make pyviz tests cover installing as a package and other new functionality (#81)
- [ ] Add reference data for notebooks
- [ ] Add a colorcet logo
- [ ] Add a section with links to other pyviz projects (nbsite, nbval, nbsmoke, autover, etc.)
- [ ] Add twitter feed listening to multiple projects
- [ ] Change 08_Custom_Interactivity.ipynb to use new RangeSelect tool
- [ ] Reduce overlap between tutorial sections

Long-term:

- [ ] Should fold in tutorial A1's material somewhere; it's odd to have it in an appendix.  It made sense when the tutorial was smaller, but now that there is always more material than can be covered, it's confusing to have it separate, so that the other material can't tell whether these concepts have been introduced.
- [ ] Need automated scripts for making at least the first pass at the site logo and favicon bitmaps from a transparent SVG source; currently edited those by hand for pyviz.org and other project sites have non-transparent logos. (See https://github.com/pyviz/nbsite/issues/40)
- [ ] Make sure everything is pip-installable as well as conda-installable (#81)
- [ ] Move topics from datashader and holoviews sites into pyviz, as most combine multiple tools.

**Comment by jlstevens** [comment]
Here are some TODO items I've noted since discussing the notebooks with @jbednar:

### Overview

- [x] Rename ``'Using HoloViews "containers" for quick, easy data exploration.'`` to ``'Working with tabular data'``.

#### ``01_Workflow_Introduction``
- [x] Add a note at the top of  to explain why this notebook is using slides unlike the others.
- [ ] Try to make the difference between holoviews and hvplot more explicit in the text. 
- [x] Re-enable the colorbar on the measles example. **Edit**: [Colorbar is already there without changing anything?]
- [x] Rename 'Dealing with large data and geo data ' heading to 'Branching out: large data, geo data, custom controls'

#### `02_Annotating_Data`

- [ ] (Optional) Try to explicitly state in the text how holoviews tries to avoids mutating the data directly.
- [x] In bullet point describing element ``kwargs`` append qualification '(Very rarely needed)'.
- [x] Change 'Here x is a convenient...' to 'Here x is a short and convenient ...'
- [x] Remove space in  ``hv.Image(arr, ['x axis','y axis'], 'h').hist()`` dimension names.

#### `03_Customizing_Visual_Appearance`

- [x] Fix 'Onwards' section to link to next tutorial nicely (also check this across notebooks)

#### ``06_Network_Graphs.ipynb``

- [x] Before datashading, point forwards to large data tutorial to help introduce datashader.

#### ``07_Geographic_Data``

- [x] At start of this tutorial, add a sentence to explain that while HoloViews and associated tools are general and handle all sorts of data, one common special case that needs attention is when people often want to situate their data on maps.

#### ``08_Custom_Interactivity``

- [ ] Try to mention new Links feature that will allow custom interactivity without needing a live server.
- [ ] Add some sentences to try and introduce ``DynamicMap`` properly (currently no introduction and very little introduction to ``HoloMap`` as it is). **Edit**: Note quite true, both containers are introduced although it is quite a minimal description each time.

#### Other tasks assigned to me

- [x] Go through the exercises notebooks and make sure sections we don't plan to skim work correctly.

#### Website

- [x] In `02_Annotating_Data` remove ``$x$`` / ``$y$`` and use backticks (MathJax rendering issue on website)
- [x] Fix broken links to exercises on website (check they work in the notebooks!). **Edit**: These links have either been fixed or they are only broken on the website (currently working in the notebook).


I expect to be able to address most of these quite quickly, as many of these are very minor tweaks.

**Comment by ceball** [comment]
> Fix data download path

Can you expand on that? I fixed one issue (https://github.com/pyviz/pyviz/pull/76) after 0.9.9 was tagged.

**Comment by jlstevens** [comment]
- [ ] One thing that should be fixed ASAP and needs a website build are the exercise links [here](http://pyviz.org/tutorial/index.html) e.g pointing to http://pyviz.org/exercises/ercise-1-making-data-visualizable.html

**Comment by jbednar** [comment]
> Can you expand on that? I fixed one issue (#76) after 0.9.9 was tagged.

So that problem is both fixed and not fixed, because we didn't tag it after fixing it.  Whether to check it off is thus highly ambiguous, until we tag.  Let's tag today once we fix the other issues and then there will be no ambiguity.

**Comment by ceball** [comment]
> One thing that should be fixed ASAP and needs a website build are the exercise links

Will happen as part of #63 (the exercises aren't currently part of the website build at all).

> So that problem is both fixed and not fixed

(just wanted to check that we were referring to the same problem)

> Add links from each tutorial notebook on to the next

Apart from that, I think it would make it simpler for people if suggested diversions/more detail were separate from what to do next in the tutorial. However, I've neither given nor received this particular tutorial, so it's only a suggestion to consider for now. (Also, the whole thing is called a tutorial, but various sections refer to 'the next tutorial' rather than e.g. 'the next section'.)

**Comment by ceball** [comment]
* [ ] 09_Operations_and_Pipelines.ipynb starts using datashader without introducing it/why to use it/that it will be described in the next section?

**Comment by jbednar** [comment]
Closing in favor of newer issues.
