### ISSUE TITLE
Strata checklist

### ISSUE THREAD

**Issue by jbednar** [holoviz/holoviz#90]
Before the next tutorial we give:

- [x] Philipp: [Panel release](https://github.com/pyviz/panel/issues/30)
- [x] Jim/Chris: Datashader release
    * [x] Fix open bugs
    * [x] Merge open PRs
- [x] Jim/Chris/Philipp: PyViz release
    * [x] Update to use panel
    * [ ] Add better exercises
    * [ ] Anything from https://github.com/pyviz/pyviz/issues/42?
    * [ ] Make sure data isn't redownloaded when updating

**Comment by jbednar** [comment]
Closing; covered by other to-do lists.
